### ISSUE TITLE
How to install this plugin?

### ISSUE THREAD

**Issue by hrvstr** [MindFlavor/Jellyfin.Plugins.Telegram#10]
Hi, I can't seem to install this plugin. What I've tried so far is:

1. Download the latest release [1.7.0.0](https://github.com/MindFlavor/Jellyfin.Plugins.Telegram/releases/tag/1.7.0.0)
2. Extract files into `/var/lib/jellyfin/plugins` (I tried placing the files in the root dir vs. creating a subfolder)
3. Restart Jellyfin
4. The plugin does not show up in the admin dashboard

**Setup:**
- Jellyfin Version: 10.7.7 (bare install from repo/no docker)
- Raspbian 10 (buster)

Am I doing something wrong here? Is the latest Jellyfin version supported?

**Comment by erkexzcx** [comment]
+1. Any instructions?

**Comment by Kingster01** [comment]
its for 10.7.0 not 10.7.7 i had same issue then realised its not been updated for 10.7.7 thats what i believe.. somewhere in repo i read its for 10.7.0

**Comment by Kingster01** [comment]
hopefully it will be updated to run on 10.7.7 as this is the version being installed now when you follow setup guide of jellyfin

**Comment by Kingster01** [comment]
Support for Jellyfin 10.7.0 Latest
@MindFlavor MindFlavor released this 17 Mar 2021
 1.7.0.0

**Comment by MindFlavor** [comment]
Hi, sorry for the late reply.
The plugin should work with version 10.7.7. I've just tested on my setup and it does (I'm on docker on Intel platform). 

I believe the problem is that you are using the x86 binaries (the ones in the GitHub release) instead of the ARM ones. Can you please try to compile from source and use that library instead?

**Comment by hrvstr** [comment]
> I believe the problem is that you are using the x86 binaries (the ones in the GitHub release) instead of the ARM ones. Can you please try to compile from source and use that library instead?

That's probably it, I didn't think about the platform specific binaries. Unfortunately I don't have the dotnet runtime installed on my Raspberry Pi and don't really have experience with build scripts so far.
