### ISSUE TITLE
Support for jellyfin 10.7.0

### ISSUE THREAD

**Issue by eldigo** [MindFlavor/Jellyfin.Plugins.Telegram#5]
Please support for jellyfin 10.7.0 as well

Thanks for the great work!

**Comment by MindFlavor** [comment]
Working on it! 👍

**Comment by MindFlavor** [comment]
The PR #6 is merged!

**Comment by CTalvio** [comment]
Just set the plugin up with 10.7.0, works great! Thank you for supporting the plugin for another version update.

Hoping this might eventually get added to the default plugin repo?

**Comment by eldigo** [comment]
Works perfect.
Thanks!

**Comment by MindFlavor** [comment]
> Hoping this might eventually get added to the default plugin repo?

I do not see why not, I've picked the most permissive license for this reason! 👍
