### ISSUE TITLE
Error 502 in Jellyfin 10.7.1

### ISSUE THREAD

**Issue by verema** [MindFlavor/Jellyfin.Plugins.Telegram#7]
Good I have problems with version 10.7.1 of jellyfin, since when I put the jellyfin plugin it does not start correctly and it gets error 502 bad Gateway, and if I delete the folder of the telegram plugin, jellyfin starts perfectly. any solution? Thank you

**Comment by verema** [comment]
ok repair

**Comment by hxreborn** [comment]
@verema mind to explain how did you fix it? I'm having the same issue

**Comment by verema** [comment]
it was a permission problem, I had the folder as owner and root group, instead of jellyfin

**Comment by verema** [comment]
> @verema mind to explain how did you fix it? I'm having the same issue

it was a permission problem, I had the folder as owner and root group, instead of jellyfin
